// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OverridableServices.Infra.Contexts;

namespace OverridableServices.Migrations
{
    [DbContext(typeof(PokemonDbContext))]
    [Migration("20220319170850_pokemoncatcher")]
    partial class pokemoncatcher
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("OverridableServices.Domain.Entities.PokemonCaught", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PokemonTrainerEmail")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PokemonCaught");
                });
#pragma warning restore 612, 618
        }
    }
}
